### PR TITLE
Add sirius device maintainer

### PR DESCRIPTION
**Pull request by mzakwan**

### CODE REVIEW

**Comment by Akianonymus** [comment]
@mzakwan when funny device maintainer 🤣

**Comment by mzakwan** [comment]
Lol,what?

**Comment by Akianonymus** [comment]
@mzakwan Joke 😆

**Comment by mzakwan** [comment]
This development still open?there are 2018 pull request still pending🤣

**Comment by aswin7469** [comment]
@mzakwan Lol first take a look at merged :)

**Pull request closed without merging**
